DROP_MOVIE_TABLE = '''
    DROP TABLE IF EXISTS MOVIE
'''

DROP_PROJECTION_TABLE = '''
    DROP TABLE IF EXISTS PROJECTION
'''

DROP_USER_TABLE = '''
    DROP TABLE IF EXISTS USER
'''

DROP_RESERVATION_TABLE = '''
    DROP TABLE IF EXISTS RESERVATION
'''


CREATE_MOVIE_TABLE = '''
    CREATE TABLE IF NOT EXISTS MOVIE (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        NAME TEXT NOT NULL,
        RATING REAL NOT NULL
    )
'''

CREATE_PROJECTION_TABLE = '''
    CREATE TABLE IF NOT EXISTS PROJECTION (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        MOVIE_ID INTEGER,
        TYPE TEXT NOT NULL,
        DATE TEXT NOT NULL,
        TIME TEXT NOT NULL,
        FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID)
    )
'''

CREATE_USER_TABLE = '''
    CREATE TABLE IF NOT EXISTS USER (
        ID INTEGER PRIMARY KEY,
        USERNAME TEXT NOT NULL,
        PASSWORD TEXT NOT NULL
    )
'''

CREATE_RESERVATION_TABLE = '''
    CREATE TABLE IF NOT EXISTS RESERVATION (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USER_ID INTEGER,
        PROJECTION_ID INTEGER,
        ROW INTEGER NOT NULL,
        COL INTEGER NOT NULL,
        FOREIGN KEY (USER_ID) REFERENCES USER(ID),
        FOREIGN KEY (PROJECTION_ID) REFERENCES PROJECTION(ID)
    )
'''

INSERT_INTO_MOVIE = '''INSERT INTO MOVIE(NAME, RATING) VALUES(?, ?)'''

INSERT_INTO_PROJECTION = '''
    INSERT INTO PROJECTION(MOVIE_ID, TYPE, DATE, TIME) VALUES(?, ?, ?, ?)
'''

INSERT_INTO_USER = '''
    INSERT INTO USER(USERNAME, PASSWORD) VALUES(?, ?)
'''

INSERT_INTO_RESERVATION = '''
    INSERT INTO RESERVATION(USER_ID, PROJECTION_ID, ROW, COL) VALUES(?, ?, ?, ?)
'''
